print()
#ჩემი მეგობრების სია.
print("Gega Sajaia")
print("Giorgi Dolidze")
print("Tornike Machitidze")
print("Tornike Wiklauri")
print("Luka Failodze")
print("Aleqsandre Qucniashvili")
print("Luka Mwedlishvili")
print("Mariam Bogveradze")
print("Giorgi Kuxianidze")
#ამოვპრინტე 20 სხვა და სხვა სიტყვა და რიცხვები (რაც ვისწავლეთ)
print("Me vswavlob msoflioshi sauketeso programirebis skolashi")
print("pirveli gakvetili dzalian momewona")
print("gakvetilebi gvitardeba")
print("2-2")
print("saatobit")
print("jer ar vicnob bavshvebs magram imedia male gavicnob")
print("ertad vixalisebt sagakvetilo processhi")
print("ertmanets shevebrdzolebit saxaliso aqtivobebshi")
print("chemi maswavlebeli batoni davit shavidzea")
print("man pirvelive gakvetilidan mogvca stimuli rom gveswavla")
print("da samomavlod kide saxliso gakvetilebs gvpirdeba")
print("pirvelive wutidanve davinaxe baton nikas da batoni davitisgan tu rogor seriozulad unda shemexeda am sperostvis")
print("chven pirvel gakvetilshi viswavlet  sololearn")
print("sololearnshi sheidzen karg codnas")
print("da aseve ufro grmad dagainteresdebat es sfero")
print("da kide mida gavxde chad da ara looser")
